// <auto-generated />

using chat.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace chat.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    internal class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("chat.Models.Message", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .UseIdentityByDefaultColumn();

                b.Property<int>("Room")
                    .HasColumnType("integer");

                b.Property<string>("UserMessage")
                    .HasColumnType("text");

                b.Property<string>("Username")
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Messages");
            });
#pragma warning restore 612, 618
        }
    }
}